jobs:
  build:
    docker:
      - image: 'hub.docker.prod.walmart.com/cimg/node:14.10.1'
    
    parallelism: 3
    resource_class: large
    # working_directory: ~/my-app
    # circleci tests glob "tests/**/test_*.sh" | xargs -n 1 echo
    steps:
      - checkout
      - run:
          command: |
            circleci tests glob tests/**/test_*.sh | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
            TESTFILES=$(circleci tests split circleci_test_files.txt)
            echo $TESTFILES
            echo $TESTFILES > circleci_test_files.txt
            cat circleci_test_files.txt | tr ' ' '\n' | sort | uniq > circleci_test_files.txt
            cat circleci_test_files.txt
            ls -lrt
            chmod a+x run-tests.sh
            ls -lrt
            ./run-tests.sh